# Site settings
title: Dissidia Tabletop RPG
email: gaius.coffee@gmail.com
# description: The Dissidia Tabletop RPG is a Pen and Paper roleplaying game that is inspired by Square Enix’s Final Fantasy series as well as Returner Games’ FFRPG. Dissidia is designed from the groud up to be minimal and modular, as well as a Minmaxer’s Delight.
baseurl: "/dissidia/"
url: "http://gaius.coffee"
twitter_username: gaiuscoffee
github_username:  GaiusCoffee

# Build settings
markdown: kramdown
exclude: [
  "bower_components",
  "bower.json"
]
gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
